name: CI

on: [pull_request]

jobs:
  test-live:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: make github-env
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
